In [2]:
#pip install numpy

In [3]:
import numpy as np

In [4]:
data1 = np.array([1, 2, 3, 4])


In [5]:
data2 = np.array([[1, 2, 4],[5,6,7]]) 

array shape and dimensions

In [6]:
print(data1.shape) 

(4,)


In [7]:
print(data2.shape)

(2, 3)


In [14]:
#array reshping
reshaped_arr = data2.reshape(3,2)
reshaped_arr

array([[1, 2],
       [4, 5],
       [6, 7]])

In [ ]:
print (data2.ndim)
print (data1.ndim)
print(reshaped_arr.ndim)

2
1
2


array indexing and slicing

In [ ]:
data1

array([1, 2, 3, 4])

In [ ]:
print(data1[2])

3


In [ ]:
print(data1[:4])
print(data1[::2])

[1 2 3 4]
[1 3]


In [ ]:
data2

array([[1, 2, 4],
       [5, 6, 7]])

In [ ]:
print(data2[1,2])

7


In [ ]:
print(data2[:,:2])

[[1 2]
 [5 6]]


array operation

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
add = a+b
add


array([ 6,  8, 10, 12])

In [ ]:
mul = a*b
mul

array([ 5, 12, 21, 32])

In [ ]:
exp_a = np.exp(a)
expo

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
log_a = np.log(a)
log_a

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
#array procastination
a

array([1, 2, 3, 4])

In [ ]:
c=5
result = a+c
result

array([6, 7, 8, 9])

Array Aggregation

In [ ]:
d1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
tot_sum = np.sum(d1)
tot_sum

np.int64(21)

In [ ]:
#sum by column wise
#0-col,1-row
col_sum = np.sum(d1,axis=0)
col_sum

array([5, 7, 9])

In [ ]:
col_sum = np.sum(d1,axis=1)
col_sum

array([ 6, 15])

In [ ]:
row_mean = np.mean(d1,axis=1)
row_mean

array([2., 5.])